import { defineStore } from "pinia";

export const usePetsStore = defineStore("pets", {
  state: () => ({
    pets: [
      // ===============================
      // 🐶 5 Dogs
      // ===============================
      {
        id: "dog1",
        type: "dog",
        name: "Rocky",
        species: "German Shepherd",
        breed: "Shepherd",
        dateOfBirth: "2022-05-10",
        sex: "Male",
        reproductiveStatus: "Neutered",
        images: ["images/dogs/German-Shepherd.jpg"],
        health: {
          vaccinated: true,
          vaccines: ["Rabies", "Parvo", "Distemper"],
          notes: "Healthy and very active.",
        },
        behavior: {
          goodWithKids: true,
          activityLevel: "High",
          personality: "Smart and playful",
        },
      },
      {
        id: "dog2",
        type: "dog",
        name: "Max",
        species: "Husky",
        breed: "Siberian Husky",
        dateOfBirth: "2021-11-22",
        sex: "Male",
        reproductiveStatus: "Not Neutered",
        images: ["images/dogs/Siberian-Husky.jpg"],
        health: {
          vaccinated: true,
          vaccines: ["Rabies"],
          notes: "Excellent condition.",
        },
        behavior: {
          goodWithKids: false,
          activityLevel: "Very High",
          personality: "Energetic",
        },
      },
      {
        id: "dog3",
        type: "dog",
        name: "Lulu",
        species: "Pomeranian",
        breed: "Pomeranian",
        dateOfBirth: "2023-02-14",
        sex: "Female",
        reproductiveStatus: "Not Spayed",
        images: ["images/dogs/Pomeranian.jpg"],
        health: { vaccinated: true, vaccines: [], notes: "" },
        behavior: {
          goodWithKids: true,
          activityLevel: "Low",
          personality: "Calm",
        },
      },
      {
        id: "dog4",
        type: "dog",
        name: "Simba",
        species: "Golden Retriever",
        breed: "Golden",
        dateOfBirth: "2021-06-03",
        sex: "Male",
        reproductiveStatus: "Neutered",
        images: ["images/dogs/Golden-Retriever.jpg"],
        health: { vaccinated: true, vaccines: [], notes: "" },
        behavior: {
          goodWithKids: true,
          activityLevel: "Medium",
          personality: "Loving",
        },
      },
      {
        id: "dog5",
        type: "dog",
        name: "Rio",
        species: "Pitbull",
        breed: "American Pitbull",
        dateOfBirth: "2020-09-01",
        sex: "Male",
        reproductiveStatus: "Neutered",
        images: ["images/dogs/American-Pitbull.jpg"],
        health: { vaccinated: true, vaccines: [], notes: "" },
        behavior: {
          goodWithKids: false,
          activityLevel: "High",
          personality: "Excellent guard dog",
        },
      },

      // ===============================
      // 🐱 4 Cats
      // ===============================
      {
        id: "cat1",
        type: "cat",
        name: "Lucy",
        species: "Persian",
        breed: "Persian Cat",
        dateOfBirth: "2023-01-02",
        sex: "Female",
        reproductiveStatus: "Not Spayed",
        images: ["images/cats/Persian-cat.jpg"],
        health: { vaccinated: true, vaccines: [], notes: "Healthy" },
        behavior: {
          goodWithKids: true,
          activityLevel: "Low",
          personality: "Gentle",
        },
      },
      {
        id: "cat2",
        type: "cat",
        name: "Milo",
        species: "British Shorthair",
        breed: "British",
        dateOfBirth: "2022-07-10",
        sex: "Male",
        reproductiveStatus: "Neutered",
        images: ["images/cats/British-Shorthair.jpg"],
        health: { vaccinated: true, vaccines: [], notes: "" },
        behavior: {
          goodWithKids: true,
          activityLevel: "Medium",
          personality: "Calm",
        },
      },
      {
        id: "cat3",
        type: "cat",
        name: "Sasha",
        species: "Siamese",
        breed: "Siamese",
        dateOfBirth: "2023-03-15",
        sex: "Female",
        reproductiveStatus: "Not Spayed",
        images: ["images/cats/Siamese.jpg"],
        health: { vaccinated: false, vaccines: [], notes: "" },
        behavior: {
          goodWithKids: false,
          activityLevel: "High",
          personality: "Curious",
        },
      },
      {
        id: "cat4",
        type: "cat",
        name: "Kitty",
        species: "Mixed",
        breed: "Mixed",
        dateOfBirth: "2021-12-30",
        sex: "Female",
        reproductiveStatus: "Spayed",
        images: ["images/cats/Mixed.jpg"],
        health: { vaccinated: true, vaccines: [], notes: "" },
        behavior: {
          goodWithKids: true,
          activityLevel: "Medium",
          personality: "Playful",
        },
      },

      // ===============================
      // 🐦 4 Birds
      // ===============================
      {
        id: "bird1",
        type: "bird",
        name: "Toka",
        species: "Parrot",
        breed: "African Grey",
        dateOfBirth: "2022-08-05",
        sex: "Male",
        reproductiveStatus: "Unknown",
        images: ["images/birds/African-Grey.jpg"],
        health: { vaccinated: false, vaccines: [], notes: "" },
        behavior: {
          goodWithKids: true,
          activityLevel: "High",
          personality: "Talkative",
        },
      },
      {
        id: "bird2",
        type: "bird",
        name: "Blue",
        species: "Budgie",
        breed: "Budgerigar",
        dateOfBirth: "2023-01-10",
        sex: "Female",
        reproductiveStatus: "Unknown",
        images: ["images/birds/Budgie.jpg"],
        health: { vaccinated: false, vaccines: [], notes: "" },
        behavior: {
          goodWithKids: true,
          activityLevel: "Medium",
          personality: "Friendly",
        },
      },
      {
        id: "bird3",
        type: "bird",
        name: "Pico",
        species: "Canary",
        breed: "Canary",
        dateOfBirth: "2022-11-10",
        sex: "Male",
        reproductiveStatus: "Unknown",
        images: ["images/birds/Canary.jpg"],
        health: { vaccinated: false, vaccines: [], notes: "" },
        behavior: {
          goodWithKids: true,
          activityLevel: "Low",
          personality: "Singer",
        },
      },
      {
        id: "bird4",
        type: "bird",
        name: "Seymour",
        species: "Cockatiel",
        breed: "Cockatiel",
        dateOfBirth: "2021-06-18",
        sex: "Male",
        reproductiveStatus: "Unknown",
        images: ["images/birds/Cockatiel.jpg"],
        health: { vaccinated: false, vaccines: [], notes: "" },
        behavior: {
          goodWithKids: true,
          activityLevel: "Low",
          personality: "Calm",
        },
      },

      // ===============================
      // 🐟 4 Fish
      // ===============================
      {
        id: "fish1",
        type: "fish",
        name: "Gold",
        species: "Goldfish",
        breed: "Common Goldfish",
        dateOfBirth: "2023-05-10",
        images: ["images/fish/Goldfish.jpg"],
        health: { vaccinated: false, notes: "Healthy" },
        behavior: { personality: "Calm" },
      },
      {
        id: "fish2",
        type: "fish",
        name: "Blue Fin",
        species: "Betta",
        breed: "Blue Betta",
        dateOfBirth: "2023-02-12",
        images: ["images/fish/Blue Betta.jpg"],
        health: { vaccinated: false, notes: "" },
        behavior: { personality: "Aggressive" },
      },
      {
        id: "fish3",
        type: "fish",
        name: "Cherry",
        species: "Shrimp",
        breed: "Cherry Shrimp",
        dateOfBirth: "2023-08-01",
        images: ["images/fish/Cherry-Shrimp.jpg"],
        health: { vaccinated: false, notes: "" },
        behavior: { personality: "Active" },
      },
      {
        id: "fish4",
        type: "fish",
        name: "Clown",
        species: "Clownfish",
        breed: "Amphiprioninae",
        dateOfBirth: "2022-09-08",
        images: ["images/fish/Clownfish.jpg"],
        health: { vaccinated: false, notes: "" },
        behavior: { personality: "Playful" },
      },

      // ===============================
      // 🦁 4 Wild Animals
      // ===============================
      {
        id: "wild1",
        type: "wild",
        name: "Leo",
        species: "Lion",
        dateOfBirth: "2023-03-20",
        images: ["images/wild/Lion.jpg"],
        health: { notes: "Strong and healthy" },
        behavior: { personality: "Majestic" },
      },
      {
        id: "wild2",
        type: "wild",
        name: "Timo",
        species: "Fox",
        dateOfBirth: "2021-10-12",
        images: ["images/wild/Fox.jpg"],
        health: { notes: "" },
        behavior: { personality: "Clever" },
      },
      {
        id: "wild3",
        type: "wild",
        name: "Panda",
        species: "Panda",
        dateOfBirth: "2019-05-10",
        images: ["images/wild/Panda.jpg"],
        health: { notes: "" },
        behavior: { personality: "Gentle" },
      },
      {
        id: "wild4",
        type: "wild",
        name: "Zebra",
        species: "Zebra",
        dateOfBirth: "2018-01-01",
        images: ["images/wild/Zebra.jpg"],
        health: { notes: "" },
        behavior: { personality: "Fast" },
      },
    ],
  }),

  getters: {
    getPetsByType: (state) => (type) =>
      state.pets.filter((pet) => pet.type === type),

    getPetById: (state) => (id) => state.pets.find((pet) => pet.id === id),
  },
});
